name: 'Security Badge Action'
description: 'Generates security badges for repository'
author: 'Tucker Weibell'

inputs:
  token:
    description: 'Github PAT token'
    required: true
  dependabot-minimum:
    description: 'Minimum allowed dependabot alerts'
    required: false
    default: 0
  dependabot-maximum:
    description: 'Maximum allowed dependabot alerts'
    required: false
    default: 10
  dependabot-badge-name:
    description: 'Maximum allowed dependabot alerts'
    required: false
    default: 'Dependabot'
  code-scanning-minimum:
    description: 'Minimum allowed code scanning alerts'
    required: false
    default: 0
  code-scanning-maximum:
    description: 'Maximum allowed code scanning alerts'
    required: false
    default: 5
  code-scanning-badge-name:
    description: 'Maximum allowed code scanning alerts'
    required: false
    default: 'Code Scanning'
  secret-scanning-minimum:
    description: 'Minimum allowed secret scanning alerts'
    required: false
    default: 0
  secret-scanning-maximum:
    description: 'Maximum allowed secret scanning alerts'
    required: false
    default: 1
  secret-scanning-badge-name:
    description: 'Maximum allowed secret scanning alerts'
    required: false
    default: 'Secret Scanning'
  gist-id:
    description: 'ID of gist you created'
    required: true
  dependabot-filename:
    description: 'Filename for dependabot badge json'
    required: false
    default: 'dependabot.json'
  code-scanning-filename:
    description: 'Filename for code scanning badge json'
    required: false
    default: 'code-scanning.json'
  secret-scanning-filename:
    description: 'Filename for secret scanning badge json'
    required: false
    default: 'secret-scanning.json'
  cache-seconds:
    description: 'How long shields.io should cache image for (min 300 seconds)'
    required: false
    default: 300
  enabled-badges:
    description: 'Defines which badges should be enabled'
    required: false
    default: depedabot, code-scanning, secret-scanning

runs:
  using: node20
  main: dist/index.js
