name: 'Security Badge Action'
description: 'Generates security badges for repository'
author: 'Tucker Weibell'

# Define your inputs here.
inputs:
  token:
    description: 'Github API token'
    required: true

# Define your outputs here.
outputs:
  dependabot-alert-count:
    description: 'Number of dependabot alerts'

runs:
  using: node20
  main: dist/index.js
