name: 'Security Badge Action'
description: 'Generates security badges for repository'
author: 'Tucker Weibell'

# Define your inputs here.
inputs:
  token:
    description: 'Github API token'
    required: true
  dependabot-minimum:
    description: 'Minimum allowed dependabot alerts'
    required: false
    default: 0
  dependabot-maximum:
    description: 'Maximum allowed dependabot alerts'
    required: false
    default: 0
  dependabot-badge-name:
    description: 'Maximum allowed dependabot alerts'
    required: false
    default: 0

# Define your outputs here.
outputs:
  dependabot-alert-count:
    description: 'Number of dependabot alerts'
  code-scanning-alert-count:
    description: 'Number of code scanning alerts'
  secret-scanning-alert-count:
    description: 'Number of secret scanning alerts'
  dependabot-svg-url:
    description: 'Url badge generated for dependabot'



runs:
  using: node20
  main: dist/index.js
